### ISSUE TITLE
Weight(.pt) and Visualization

### ISSUE THREAD

**Issue by MPCheng-ZW** [YoushaaMurhij/OFMPNet#3]
1. Wights(.pt)
I  assume the model is set to run for 15 epochs, which will generate epoch_1.pt to epoch_15.pt when I execute the train.py. However, how can I determine which set of weights is the best? In other words, which .pt file should I use in inference.py for testing? I think the final .pt file (epoch_15.pt) may not necessarily be the best ones. Shouldn't a best.pt file be generated to indicate the best weights?
![Weight](https://github.com/user-attachments/assets/71abc47f-c1b2-44b0-8a7b-9bc17e47c3c2)

2. Visualization
In the visualize.py, which '--file_dir'  should I use? Should it be 
'Waymo_Dataset/uncompressed/preprocessed_data/tf_example/val_numpy' or 'Waymo_Dataset/uncompressed/preprocessed_data/tf_example/test_numpy' ? I think it should be test_numpy, it's right?
![Visual](https://github.com/user-attachments/assets/e6c90fe9-c4d4-44f4-8714-c5d4feca714e)

Thanks!

**Comment by YoushaaMurhij** [comment]
1- There is a validation step after each epoch.
2- both should work but test data does not contain GT.
